app:
  port: ':33333'
  auth: 'qa'
db:
  type: 'mysql'
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  passwd: 'root'
  dbName: 'scan'
logger:
  fileName: 'qa'
  filePath: 'log'
jwt:
  signKey: 'qa'
  timeout: '10'
  iss: 'qa'
  bufferTime: '5'
file:
  path: 'docs/upload'

shell:
  name: 'test.sh'
  absPath: '/download'
  localPath: './docs/shell'
